# -*- coding: utf-8 -*-
"""MeuJogoParouImpar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10V6epcUWXukGB8VLFgtmB4axXVAW8zvD
"""

jogador1 = input('-> Digite o nome do primeiro jogador:')
jogador2 = input('-> Digite o nome do segundo jogador:')

print(f'// quem escolhe primeiro, {jogador1} ou {jogador2}?')
primeiro_jogador = input(f'-> Digite 1 para escolher {jogador1} ou 2 para escolher {jogador2}.')
segundo_jogador = None

if primeiro_jogador =='1':
  primeiro_jogador = jogador1
  segundo_jogador = jogador2

elif primeiro_jogador =='2':
  primeiro_jogador = jogador2
  segundo_jogador = jogador1

print ('// Digite 0 para escolher QUARTA ou 1 para escolher SEXTA')
escolha = input (f'-> {primeiro_jogador}, você quer SEXTA ou QUARTA ?')
escolha2 = None

if escolha == 'SEXTA' or escolha == 'SEXTA' or escolha == '1':
  escolha = 'SEXTA'
  escolha2 = 'QUARTA'

elif escolha == 'QUARTA' or escolha == '0':
  escolha = 'QUARTA'
  escolha2 = 'SEXTA'

print(f'//{segundo_jogador}, você ficou com a {escolha2}.')

numero1 = int(input(f'{primeiro_jogador}, escolha um numero:'))
numero2 = int(input(f'{segundo_jogador}, escolha um numero:'))

soma = numero1 + numero2

if soma % 2 == 0:
  vencedor = 'QUARTA'
else:
  vencedor = 'SEXTA,'

if vencedor == escolha:
  print(f'// {primeiro_jogador} venceu!')
else:
  print(f'// {segundo_jogador} venceu!')

